#!/usr/bin/python

import sys
import socket

for arg in sys.argv[1:]:
  #print arg
  if arg == '-c':
    print 'Cliente'
    for aux in sys.argv[2:3]:
      ip,port=aux.split(":")
      print ip
      print port
    for auxInput in sys.argv[3:4]:
      print auxInput
    for auxOutput in sys.argv[4:]:
      print auxOutput
    HOST = ip
    PORT = port
    tcp = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    dest = (HOST, PORT)
    tcp.connect(dest)
    msg = raw_input()
    while msg <> '\x18':
      tcp.send (msg)
      msg = tcp.recv(1024)
      tcp.close()

  if arg == '-s':
    print 'Servidor'
    for port in sys.argv[2:3]:
      print port
    for auxInput in sys.argv[3:4]:
      print auxInput
    for auxOutput in sys.argv[4:]:
      print auxOutput
    HOST = ''
    PORT = port
    tcp = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    orig = (HOST, PORT)
    #tcp.bind(orig)
    tcp.listen(1)
    while True:
      con, cliente = tcp.accept()
      con.close()
